# Makefile for uClibc
#
# Copyright (C) 2014 Stefan Kristiansson <stefan.kristiansson@saunalahti.fi>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.

CSRC-y :=

SSRC-y := setjmp.S __longjmp.S
